/*
 * Copyright (c) 2009-2019 ARM Limited. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @file     rt32f7.h
 * @brief    CMSIS HeaderFile
 * @version  1
 * @date     Wed Apr 29 09:13:11 2026
 * @note     Generated by SVDConv V3.3.46 from File 'rt32f7.svd',
 *           last modified on Wed Apr 29 09:12:26 2026
 */


/** @addtogroup RealTime Semiconductor Co. LTD
  * @{
  */


/** @addtogroup rt32f7
  * @{
  */


#ifndef RT32F7_H
#define RT32F7_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* =======================================  ARM Cortex-M7 Specific Interrupt Numbers  ======================================== */
  Reset_IRQn                = -15,              /*!< -15  Reset Vector, invoked on Power up and warm reset                     */
  NonMaskableInt_IRQn       = -14,              /*!< -14  Non maskable Interrupt, cannot be stopped or preempted               */
  HardFault_IRQn            = -13,              /*!< -13  Hard Fault, all classes of Fault                                     */
  MemoryManagement_IRQn     = -12,              /*!< -12  Memory Management, MPU mismatch, including Access Violation
                                                     and No Match                                                              */
  BusFault_IRQn             = -11,              /*!< -11  Bus Fault, Pre-Fetch-, Memory Access Fault, other address/memory
                                                     related Fault                                                             */
  UsageFault_IRQn           = -10,              /*!< -10  Usage Fault, i.e. Undef Instruction, Illegal State Transition        */
  SVCall_IRQn               =  -5,              /*!< -5 System Service Call via SVC instruction                                */
  DebugMonitor_IRQn         =  -4,              /*!< -4 Debug Monitor                                                          */
  PendSV_IRQn               =  -2,              /*!< -2 Pendable request for system service                                    */
  SysTick_IRQn              =  -1,              /*!< -1 System Tick Timer                                                      */
/* ===========================================  rt32f7 Specific Interrupt Numbers  =========================================== */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */

/* ===========================  Configuration of the ARM Cortex-M7 Processor and Core Peripherals  =========================== */
#define __CM7_REV                 0x0102U       /*!< CM7 Core Revision                                                         */
#define __NVIC_PRIO_BITS               4        /*!< Number of Bits used for Priority Levels                                   */
#define __Vendor_SysTickConfig         0        /*!< Set to 1 if different SysTick Config is used                              */
#define __MPU_PRESENT                  1        /*!< MPU present                                                               */
#define __FPU_PRESENT                  1        /*!< FPU present                                                               */
#define __FPU_DP                       1        /*!< Double Precision FPU                                                      */
#define __ICACHE_PRESENT               1        /*!< Instruction Cache present                                                 */
#define __DCACHE_PRESENT               1        /*!< Data Cache present                                                        */
#define __ITCM_PRESENT                 1        /*!< Instruction TCM present                                                   */
#define __DTCM_PRESENT                 1        /*!< Data TCM present                                                          */


/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_cm7.h"                           /*!< ARM Cortex-M7 processor and core peripherals                              */
#include "system_rt32f7.h"                      /*!< rt32f7 System                                                             */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           FLASH                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief Flash Controller (FLASH)
  */

typedef struct {                                /*!< FLASH Structure                                                           */
  __IM  uint32_t  RESERVED;

  union {
    __OM  uint32_t reg;                         /*!< FLASH Unlock Register 1                                                   */

    struct {
      __OM  uint32_t KEY        : 32;           /*!< FLASH [31:0] Bits: Write lock / unlock key                                */
    } bit;
  } UNLOCKR1;
  __IM  uint32_t  RESERVED1;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Status Register 1                                                   */

    struct {
      __IM  uint32_t BUSY       : 1;            /*!< FLASH BUSY Bit: Bank 1 busy flag                                          */
            uint32_t            : 4;
      __IOM uint32_t EOP        : 1;            /*!< FLASH EOP Bit: Bank 1 end of operation flag                               */
            uint32_t            : 26;
    } bit;
  } SR1;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Control Register 1                                                  */

    struct {
      __IOM uint32_t PGEN       : 1;            /*!< FLASH PGEN Bit: Enable / Disable bank 1 programming                       */
      __IOM uint32_t SEREN      : 1;            /*!< FLASH SEREN Bit: Enable / Disable bank 1 sector erasure                   */
      __IOM uint32_t BEREN      : 1;            /*!< FLASH BEREN Bit: Enable / Disable bank 1 main block erasure               */
            uint32_t            : 3;
      __IOM uint32_t START      : 1;            /*!< FLASH START Bit: Start bank 1 operation                                   */
      __IOM uint32_t LOCK       : 1;            /*!< FLASH LOCK Bit: Lock bank 1                                               */
      __IOM uint32_t SYSLOCK    : 1;            /*!< FLASH SYSLOCK Bit: Lock system block                                      */
            uint32_t            : 23;
    } bit;
  } CR1;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Address Register 1                                                  */

    struct {
      __IOM uint32_t ADDR       : 32;           /*!< FLASH [31:0] Bits: Bank 1 operation address                               */
    } bit;
  } AR1;
  __IM  uint32_t  RESERVED2[19];

  union {
    __OM  uint32_t reg;                         /*!< FLASH System Block Unlock Register                                        */

    struct {
      __OM  uint32_t KEY        : 32;           /*!< FLASH [31:0] Bits: Write lock / unlock key                                */
    } bit;
  } SYSUNLOCKR;
  __IM  uint32_t  RESERVED3;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Boot Address Register 1                                             */

    struct {
      __IOM uint32_t ADDR       : 32;           /*!< FLASH [31:0] Bits: Core 1 default interrupt vector table start
                                                     address                                                                   */
    } bit;
  } BOOTAR1;
  __IM  uint32_t  RESERVED4[8];

  union {
    __IOM uint32_t reg;                         /*!< FLASH Boot Address Register 1                                             */

    struct {
      __IOM uint32_t ADDR       : 32;           /*!< FLASH [31:0] Bits: Core 2 default interrupt vector table start
                                                     address                                                                   */
    } bit;
  } BOOTAR2;
  __IM  uint32_t  RESERVED5[28];

  union {
    __OM  uint32_t reg;                         /*!< FLASH Unlock Register 2                                                   */

    struct {
      __OM  uint32_t KEY        : 32;           /*!< FLASH [31:0] Bits: Write lock / unlock key                                */
    } bit;
  } UNLOCKR2;
  __IM  uint32_t  RESERVED6;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Status Register 2                                                   */

    struct {
      __IM  uint32_t BUSY       : 1;            /*!< FLASH BUSY Bit: Bank 2 busy flag                                          */
            uint32_t            : 4;
      __IOM uint32_t EOP        : 1;            /*!< FLASH EOP Bit: Bank 2 end of operation flag                               */
            uint32_t            : 26;
    } bit;
  } SR2;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Control Register 2                                                  */

    struct {
      __IOM uint32_t PGEN       : 1;            /*!< FLASH PGEN Bit: Enable / Disable bank 2 programming                       */
      __IOM uint32_t SEREN      : 1;            /*!< FLASH SEREN Bit: Enable / Disable bank 2 sector erasure                   */
      __IOM uint32_t BEREN      : 1;            /*!< FLASH BEREN Bit: Enable / Disable bank 2 main block erasure               */
            uint32_t            : 3;
      __IOM uint32_t START      : 1;            /*!< FLASH START Bit: Start bank 2 operation                                   */
      __IOM uint32_t LOCK       : 1;            /*!< FLASH LOCK Bit: Lock bank 2                                               */
            uint32_t            : 24;
    } bit;
  } CR2;

  union {
    __IOM uint32_t reg;                         /*!< FLASH Address Register 2                                                  */

    struct {
      __IOM uint32_t ADDR       : 32;           /*!< FLASH [31:0] Bits: Bank 2 opration address                                */
    } bit;
  } AR2;
} FLASH_Type;                                   /*!< Size = 280 (0x118)                                                        */



/* =========================================================================================================================== */
/* ================                                           GPIOA                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief General Purpose Input Output A (GPIOA)
  */

typedef struct {                                /*!< GPIOA Structure                                                           */
  __IM  uint32_t  RESERVED[3];

  union {
    __IOM uint32_t reg;                         /*!< GPIOA IO Multiplexer Alternate Function Number Register 1                 */

    struct {
      __IOM uint32_t PIN0       : 2;            /*!< GPIOA [1:0] Bits: Select pin 0 alternate function number                  */
      __IOM uint32_t PIN1       : 2;            /*!< GPIOA [1:0] Bits: Select pin 1 alternate function number                  */
      __IOM uint32_t PIN2       : 2;            /*!< GPIOA [1:0] Bits: Select pin 2 alternate function number                  */
      __IOM uint32_t PIN3       : 2;            /*!< GPIOA [1:0] Bits: Select pin 3 alternate function number                  */
      __IOM uint32_t PIN4       : 2;            /*!< GPIOA [1:0] Bits: Select pin 4 alternate function number                  */
      __IOM uint32_t PIN5       : 2;            /*!< GPIOA [1:0] Bits: Select pin 5 alternate function number                  */
      __IOM uint32_t PIN6       : 2;            /*!< GPIOA [1:0] Bits: Select pin 6 alternate function number                  */
      __IOM uint32_t PIN7       : 2;            /*!< GPIOA [1:0] Bits: Select pin 7 alternate function number                  */
      __IOM uint32_t PIN8       : 2;            /*!< GPIOA [1:0] Bits: Select pin 8 alternate function number                  */
      __IOM uint32_t PIN9       : 2;            /*!< GPIOA [1:0] Bits: Select pin 9 alternate function number                  */
      __IOM uint32_t PIN10      : 2;            /*!< GPIOA [1:0] Bits: Select pin 10 alternate function number                 */
      __IOM uint32_t PIN11      : 2;            /*!< GPIOA [1:0] Bits: Select pin 11 alternate function number                 */
      __IOM uint32_t PIN12      : 2;            /*!< GPIOA [1:0] Bits: Select pin 12 alternate function number                 */
      __IOM uint32_t PIN13      : 2;            /*!< GPIOA [1:0] Bits: Select pin 13 alternate function number                 */
      __IOM uint32_t PIN14      : 2;            /*!< GPIOA [1:0] Bits: Select pin 14 alternate function number                 */
      __IOM uint32_t PIN15      : 2;            /*!< GPIOA [1:0] Bits: Select pin 15 alternate function number                 */
    } bit;
  } AFR1;

  union {
    __IOM uint32_t reg;                         /*!< GPIOA IO Multiplexer Alternate Function Number Register 2                 */

    struct {
      __IOM uint32_t PIN16      : 2;            /*!< GPIOA [1:0] Bits: Select pin 16 alternate function number                 */
      __IOM uint32_t PIN17      : 2;            /*!< GPIOA [1:0] Bits: Select pin 17 alternate function number                 */
      __IOM uint32_t PIN18      : 2;            /*!< GPIOA [1:0] Bits: Select pin 18 alternate function number                 */
      __IOM uint32_t PIN19      : 2;            /*!< GPIOA [1:0] Bits: Select pin 19 alternate function number                 */
      __IOM uint32_t PIN20      : 2;            /*!< GPIOA [1:0] Bits: Select pin 20 alternate function number                 */
      __IOM uint32_t PIN21      : 2;            /*!< GPIOA [1:0] Bits: Select pin 21 alternate function number                 */
      __IOM uint32_t PIN22      : 2;            /*!< GPIOA [1:0] Bits: Select pin 22 alternate function number                 */
      __IOM uint32_t PIN23      : 2;            /*!< GPIOA [1:0] Bits: Select pin 23 alternate function number                 */
      __IOM uint32_t PIN24      : 2;            /*!< GPIOA [1:0] Bits: Select pin 24 alternate function number                 */
      __IOM uint32_t PIN25      : 2;            /*!< GPIOA [1:0] Bits: Select pin 25 alternate function number                 */
      __IOM uint32_t PIN26      : 2;            /*!< GPIOA [1:0] Bits: Select pin 26 alternate function number                 */
      __IOM uint32_t PIN27      : 2;            /*!< GPIOA [1:0] Bits: Select pin 27 alternate function number                 */
      __IOM uint32_t PIN28      : 2;            /*!< GPIOA [1:0] Bits: Select pin 28 alternate function number                 */
      __IOM uint32_t PIN29      : 2;            /*!< GPIOA [1:0] Bits: Select pin 29 alternate function number                 */
      __IOM uint32_t PIN30      : 2;            /*!< GPIOA [1:0] Bits: Select pin 30 alternate function number                 */
      __IOM uint32_t PIN31      : 2;            /*!< GPIOA [1:0] Bits: Select pin 31 alternate function number                 */
    } bit;
  } AFR2;
  __IM  uint32_t  RESERVED1[4];

  union {
    __IOM uint32_t reg;                         /*!< GPIOA Analog Mode Select Register                                         */

    struct {
      __IOM uint32_t PIN0       : 1;            /*!< GPIOA PIN0 Bit: Select pin 0 analog mode or digital mode                  */
      __IOM uint32_t PIN1       : 1;            /*!< GPIOA PIN1 Bit: Select pin 1 analog mode or digital mode                  */
      __IOM uint32_t PIN2       : 1;            /*!< GPIOA PIN2 Bit: Select pin 2 analog mode or digital mode                  */
      __IOM uint32_t PIN3       : 1;            /*!< GPIOA PIN3 Bit: Select pin 3 analog mode or digital mode                  */
      __IOM uint32_t PIN4       : 1;            /*!< GPIOA PIN4 Bit: Select pin 4 analog mode or digital mode                  */
      __IOM uint32_t PIN5       : 1;            /*!< GPIOA PIN5 Bit: Select pin 5 analog mode or digital mode                  */
      __IOM uint32_t PIN6       : 1;            /*!< GPIOA PIN6 Bit: Select pin 6 analog mode or digital mode                  */
      __IOM uint32_t PIN7       : 1;            /*!< GPIOA PIN7 Bit: Select pin 7 analog mode or digital mode                  */
      __IOM uint32_t PIN8       : 1;            /*!< GPIOA PIN8 Bit: Select pin 8 analog mode or digital mode                  */
      __IOM uint32_t PIN9       : 1;            /*!< GPIOA PIN9 Bit: Select pin 9 analog mode or digital mode                  */
      __IOM uint32_t PIN10      : 1;            /*!< GPIOA PIN10 Bit: Select pin 10 analog mode or digital mode                */
      __IOM uint32_t PIN11      : 1;            /*!< GPIOA PIN11 Bit: Select pin 11 analog mode or digital mode                */
      __IOM uint32_t PIN12      : 1;            /*!< GPIOA PIN12 Bit: Select pin 12 analog mode or digital mode                */
      __IOM uint32_t PIN13      : 1;            /*!< GPIOA PIN13 Bit: Select pin 13 analog mode or digital mode                */
      __IOM uint32_t PIN14      : 1;            /*!< GPIOA PIN14 Bit: Select pin 14 analog mode or digital mode                */
      __IOM uint32_t PIN15      : 1;            /*!< GPIOA PIN15 Bit: Select pin 15 analog mode or digital mode                */
      __IOM uint32_t PIN16      : 1;            /*!< GPIOA PIN16 Bit: Select pin 16 analog mode or digital mode                */
      __IOM uint32_t PIN17      : 1;            /*!< GPIOA PIN17 Bit: Select pin 17 analog mode or digital mode                */
      __IOM uint32_t PIN18      : 1;            /*!< GPIOA PIN18 Bit: Select pin 18 analog mode or digital mode                */
      __IOM uint32_t PIN19      : 1;            /*!< GPIOA PIN19 Bit: Select pin 19 analog mode or digital mode                */
      __IOM uint32_t PIN20      : 1;            /*!< GPIOA PIN20 Bit: Select pin 20 analog mode or digital mode                */
      __IOM uint32_t PIN21      : 1;            /*!< GPIOA PIN21 Bit: Select pin 21 analog mode or digital mode                */
      __IOM uint32_t PIN22      : 1;            /*!< GPIOA PIN22 Bit: Select pin 22 analog mode or digital mode                */
      __IOM uint32_t PIN23      : 1;            /*!< GPIOA PIN23 Bit: Select pin 23 analog mode or digital mode                */
      __IOM uint32_t PIN24      : 1;            /*!< GPIOA PIN24 Bit: Select pin 24 analog mode or digital mode                */
      __IOM uint32_t PIN25      : 1;            /*!< GPIOA PIN25 Bit: Select pin 25 analog mode or digital mode                */
      __IOM uint32_t PIN26      : 1;            /*!< GPIOA PIN26 Bit: Select pin 26 analog mode or digital mode                */
      __IOM uint32_t PIN27      : 1;            /*!< GPIOA PIN27 Bit: Select pin 27 analog mode or digital mode                */
      __IOM uint32_t PIN28      : 1;            /*!< GPIOA PIN28 Bit: Select pin 28 analog mode or digital mode                */
      __IOM uint32_t PIN29      : 1;            /*!< GPIOA PIN29 Bit: Select pin 29 analog mode or digital mode                */
      __IOM uint32_t PIN30      : 1;            /*!< GPIOA PIN30 Bit: Select pin 30 analog mode or digital mode                */
      __IOM uint32_t PIN31      : 1;            /*!< GPIOA PIN31 Bit: Select pin 31 analog mode or digital mode                */
    } bit;
  } AMSELR;

  union {
    __IOM uint32_t reg;                         /*!< GPIOA IO Multiplexer Alternate Function Group Number Register
                                                     1                                                                         */

    struct {
      __IOM uint32_t PIN0       : 2;            /*!< GPIOA [1:0] Bits: Select pin 0 alternate function group number            */
      __IOM uint32_t PIN1       : 2;            /*!< GPIOA [1:0] Bits: Select pin 1 alternate function group number            */
      __IOM uint32_t PIN2       : 2;            /*!< GPIOA [1:0] Bits: Select pin 2 alternate function group number            */
      __IOM uint32_t PIN3       : 2;            /*!< GPIOA [1:0] Bits: Select pin 3 alternate function group number            */
      __IOM uint32_t PIN4       : 2;            /*!< GPIOA [1:0] Bits: Select pin 4 alternate function group number            */
      __IOM uint32_t PIN5       : 2;            /*!< GPIOA [1:0] Bits: Select pin 5 alternate function group number            */
      __IOM uint32_t PIN6       : 2;            /*!< GPIOA [1:0] Bits: Select pin 6 alternate function group number            */
      __IOM uint32_t PIN7       : 2;            /*!< GPIOA [1:0] Bits: Select pin 7 alternate function group number            */
      __IOM uint32_t PIN8       : 2;            /*!< GPIOA [1:0] Bits: Select pin 8 alternate function group number            */
      __IOM uint32_t PIN9       : 2;            /*!< GPIOA [1:0] Bits: Select pin 9 alternate function group number            */
      __IOM uint32_t PIN10      : 2;            /*!< GPIOA [1:0] Bits: Select pin 10 alternate function group number           */
      __IOM uint32_t PIN11      : 2;            /*!< GPIOA [1:0] Bits: Select pin 11 alternate function group number           */
      __IOM uint32_t PIN12      : 2;            /*!< GPIOA [1:0] Bits: Select pin 12 alternate function group number           */
      __IOM uint32_t PIN13      : 2;            /*!< GPIOA [1:0] Bits: Select pin 13 alternate function group number           */
      __IOM uint32_t PIN14      : 2;            /*!< GPIOA [1:0] Bits: Select pin 14 alternate function group number           */
      __IOM uint32_t PIN15      : 2;            /*!< GPIOA [1:0] Bits: Select pin 15 alternate function group number           */
    } bit;
  } AFGR1;

  union {
    __IOM uint32_t reg;                         /*!< GPIOA IO Multiplexer Alternate Function Group Number Register
                                                     2                                                                         */

    struct {
      __IOM uint32_t PIN16      : 2;            /*!< GPIOA [1:0] Bits: Select pin 16 alternate function group number           */
      __IOM uint32_t PIN17      : 2;            /*!< GPIOA [1:0] Bits: Select pin 17 alternate function group number           */
      __IOM uint32_t PIN18      : 2;            /*!< GPIOA [1:0] Bits: Select pin 18 alternate function group number           */
      __IOM uint32_t PIN19      : 2;            /*!< GPIOA [1:0] Bits: Select pin 19 alternate function group number           */
      __IOM uint32_t PIN20      : 2;            /*!< GPIOA [1:0] Bits: Select pin 20 alternate function group number           */
      __IOM uint32_t PIN21      : 2;            /*!< GPIOA [1:0] Bits: Select pin 21 alternate function group number           */
      __IOM uint32_t PIN22      : 2;            /*!< GPIOA [1:0] Bits: Select pin 22 alternate function group number           */
      __IOM uint32_t PIN23      : 2;            /*!< GPIOA [1:0] Bits: Select pin 23 alternate function group number           */
      __IOM uint32_t PIN24      : 2;            /*!< GPIOA [1:0] Bits: Select pin 24 alternate function group number           */
      __IOM uint32_t PIN25      : 2;            /*!< GPIOA [1:0] Bits: Select pin 25 alternate function group number           */
      __IOM uint32_t PIN26      : 2;            /*!< GPIOA [1:0] Bits: Select pin 26 alternate function group number           */
      __IOM uint32_t PIN27      : 2;            /*!< GPIOA [1:0] Bits: Select pin 27 alternate function group number           */
      __IOM uint32_t PIN28      : 2;            /*!< GPIOA [1:0] Bits: Select pin 28 alternate function group number           */
      __IOM uint32_t PIN29      : 2;            /*!< GPIOA [1:0] Bits: Select pin 29 alternate function group number           */
      __IOM uint32_t PIN30      : 2;            /*!< GPIOA [1:0] Bits: Select pin 30 alternate function group number           */
      __IOM uint32_t PIN31      : 2;            /*!< GPIOA [1:0] Bits: Select pin 31 alternate function group number           */
    } bit;
  } AFGR2;
} GPIO_Type;                                    /*!< Size = 48 (0x30)                                                          */



/* =========================================================================================================================== */
/* ================                                            RCC                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Reset and Clock Controller (RCC)
  */

typedef struct {                                /*!< RCC Structure                                                             */
  __IM  uint32_t  RESERVED[28];

  union {
    __IOM uint32_t reg;                         /*!< RCC AHB Peripheral Clock Enable Register 1                                */

    struct {
            uint32_t            : 16;
      __IOM uint32_t GPIOAEN    : 1;            /*!< RCC GPIOAEN Bit: Enable / Disable GPIOA peripheral clock                  */
            uint32_t            : 15;
    } bit;
  } AHBEN1;
  __IM  uint32_t  RESERVED1[7];

  union {
    __IOM uint32_t reg;                         /*!< RCC APB Peripheral Clock Enable Register 5                                */

    struct {
      __IOM uint32_t UART1EN    : 1;            /*!< RCC UART1EN Bit: Enable / Disable UART1 peripheral clock                  */
            uint32_t            : 31;
    } bit;
  } APBEN5;
  __IM  uint32_t  RESERVED2[51];

  union {
    __OM  uint32_t reg;                         /*!< RCC Unlock Register                                                       */

    struct {
      __OM  uint32_t KEY        : 32;           /*!< RCC [31:0] Bits: Write lock / unlock key                                  */
    } bit;
  } UNLOCKR;
} RCC_Type;                                     /*!< Size = 356 (0x164)                                                        */



/* =========================================================================================================================== */
/* ================                                          SYSCTRL                                          ================ */
/* =========================================================================================================================== */


/**
  * @brief System Controller (SYSCTRL)
  */

typedef struct {                                /*!< SYSCTRL Structure                                                         */
  __IM  uint32_t  RESERVED[38];

  union {
    __IOM uint32_t reg;                         /*!< SYSCTRL Enhanced Protect Register 1                                       */

    struct {
      __IOM uint32_t GPIOADIS   : 1;            /*!< SYSCTRL GPIOADIS Bit: Lock / Unlock GPIOA registers                       */
            uint32_t            : 31;
    } bit;
  } EPROTR3;
  __IM  uint32_t  RESERVED1;

  union {
    __IOM uint32_t reg;                         /*!< SYSCTRL Unlock Register                                                   */

    struct {
      __IOM uint32_t KEY        : 32;           /*!< SYSCTRL [31:0] Bits: Write lock / unlock key                              */
    } bit;
  } UNLOCKR;
} SYSCTRL_Type;                                 /*!< Size = 164 (0xa4)                                                         */



/* =========================================================================================================================== */
/* ================                                           UART1                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief Universal Asynchronous Receiver Transmitter 1 (UART1)
  */

typedef struct {                                /*!< UART1 Structure                                                           */

  union {
    __IOM uint32_t reg;                         /*!< UART1 Control Register 1                                                  */

    struct {
            uint32_t            : 1;
      __IOM uint32_t RST        : 1;            /*!< UART1 RST Bit: Reset / Release UART module                                */
            uint32_t            : 30;
    } bit;
  } CR1;
  __IM  uint32_t  RESERVED[3];

  union {
    __IOM uint32_t reg;                         /*!< UART1 Control Register 2                                                  */

    struct {
      __IOM uint32_t DIV        : 13;           /*!< UART1 [12:0] Bits: Clock divisor                                          */
            uint32_t            : 4;
      __IOM uint32_t DESEN      : 1;            /*!< UART1 DESEN Bit: Enable / Disable double edge sampling                    */
            uint32_t            : 6;
      __IOM uint32_t OSR        : 5;            /*!< UART1 [4:0] Bits: Over sampling rate                                      */
            uint32_t            : 3;
    } bit;
  } CR2;

  union {
    __IOM uint32_t reg;                         /*!< UART1 Control and Status Register 1                                       */

    struct {
            uint32_t            : 22;
      __IM  uint32_t TXC        : 1;            /*!< UART1 TXC Bit: TX complete flag                                           */
      __IM  uint32_t TXRDY      : 1;            /*!< UART1 TXRDY Bit: TX buffer ready flag                                     */
            uint32_t            : 8;
    } bit;
  } CSR1;

  union {
    __IOM uint32_t reg;                         /*!< UART1 Control Register 3                                                  */

    struct {
            uint32_t            : 19;
      __IOM uint32_t TXEN       : 1;            /*!< UART1 TXEN Bit: Enable / Disable TX module                                */
            uint32_t            : 12;
    } bit;
  } CR3;

  union {
    __IOM uint32_t reg;                         /*!< UART1 Data Register                                                       */

    struct {
      __IOM uint32_t DATA       : 8;            /*!< UART1 [7:0] Bits: Data                                                    */
            uint32_t            : 24;
    } bit;
  } DR;
} UART_Type;                                    /*!< Size = 32 (0x20)                                                          */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define FLASH_BASE                  0x400B1000UL
#define GPIOA_BASE                  0x400A0000UL
#define RCC_BASE                    0x400B0000UL
#define SYSCTRL_BASE                0x40037000UL
#define UART1_BASE                  0x40042000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define FLASH                       ((FLASH_Type*)             FLASH_BASE)
#define GPIOA                       ((GPIO_Type*)              GPIOA_BASE)
#define RCC                         ((RCC_Type*)               RCC_BASE)
#define SYSCTRL                     ((SYSCTRL_Type*)           SYSCTRL_BASE)
#define UART1                       ((UART_Type*)              UART1_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================================================================================================== */
/* ================                                Pos/Mask Peripheral Section                                ================ */
/* =========================================================================================================================== */


/** @addtogroup PosMask_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                           FLASH                                           ================ */
/* =========================================================================================================================== */

/* =======================================================  UNLOCKR1  ======================================================== */
#define FLASH_UNLOCKR1_KEY_Pos            (0UL)                     /*!< KEY (Bit 0)                                           */
#define FLASH_UNLOCKR1_KEY_Msk            (0xffffffffUL)            /*!< KEY (Bitfield-Mask: 0xffffffff)                       */
/* ==========================================================  SR1  ========================================================== */
#define FLASH_SR1_EOP_Pos                 (5UL)                     /*!< EOP (Bit 5)                                           */
#define FLASH_SR1_EOP_Msk                 (0x20UL)                  /*!< EOP (Bitfield-Mask: 0x01)                             */
#define FLASH_SR1_BUSY_Pos                (0UL)                     /*!< BUSY (Bit 0)                                          */
#define FLASH_SR1_BUSY_Msk                (0x1UL)                   /*!< BUSY (Bitfield-Mask: 0x01)                            */
/* ==========================================================  CR1  ========================================================== */
#define FLASH_CR1_SYSLOCK_Pos             (8UL)                     /*!< SYSLOCK (Bit 8)                                       */
#define FLASH_CR1_SYSLOCK_Msk             (0x100UL)                 /*!< SYSLOCK (Bitfield-Mask: 0x01)                         */
#define FLASH_CR1_LOCK_Pos                (7UL)                     /*!< LOCK (Bit 7)                                          */
#define FLASH_CR1_LOCK_Msk                (0x80UL)                  /*!< LOCK (Bitfield-Mask: 0x01)                            */
#define FLASH_CR1_START_Pos               (6UL)                     /*!< START (Bit 6)                                         */
#define FLASH_CR1_START_Msk               (0x40UL)                  /*!< START (Bitfield-Mask: 0x01)                           */
#define FLASH_CR1_BEREN_Pos               (2UL)                     /*!< BEREN (Bit 2)                                         */
#define FLASH_CR1_BEREN_Msk               (0x4UL)                   /*!< BEREN (Bitfield-Mask: 0x01)                           */
#define FLASH_CR1_SEREN_Pos               (1UL)                     /*!< SEREN (Bit 1)                                         */
#define FLASH_CR1_SEREN_Msk               (0x2UL)                   /*!< SEREN (Bitfield-Mask: 0x01)                           */
#define FLASH_CR1_PGEN_Pos                (0UL)                     /*!< PGEN (Bit 0)                                          */
#define FLASH_CR1_PGEN_Msk                (0x1UL)                   /*!< PGEN (Bitfield-Mask: 0x01)                            */
/* ==========================================================  AR1  ========================================================== */
#define FLASH_AR1_ADDR_Pos                (0UL)                     /*!< ADDR (Bit 0)                                          */
#define FLASH_AR1_ADDR_Msk                (0xffffffffUL)            /*!< ADDR (Bitfield-Mask: 0xffffffff)                      */
/* ======================================================  SYSUNLOCKR  ======================================================= */
#define FLASH_SYSUNLOCKR_KEY_Pos          (0UL)                     /*!< KEY (Bit 0)                                           */
#define FLASH_SYSUNLOCKR_KEY_Msk          (0xffffffffUL)            /*!< KEY (Bitfield-Mask: 0xffffffff)                       */
/* ========================================================  BOOTAR1  ======================================================== */
#define FLASH_BOOTAR1_ADDR_Pos            (0UL)                     /*!< ADDR (Bit 0)                                          */
#define FLASH_BOOTAR1_ADDR_Msk            (0xffffffffUL)            /*!< ADDR (Bitfield-Mask: 0xffffffff)                      */
/* ========================================================  BOOTAR2  ======================================================== */
#define FLASH_BOOTAR2_ADDR_Pos            (0UL)                     /*!< ADDR (Bit 0)                                          */
#define FLASH_BOOTAR2_ADDR_Msk            (0xffffffffUL)            /*!< ADDR (Bitfield-Mask: 0xffffffff)                      */
/* =======================================================  UNLOCKR2  ======================================================== */
#define FLASH_UNLOCKR2_KEY_Pos            (0UL)                     /*!< KEY (Bit 0)                                           */
#define FLASH_UNLOCKR2_KEY_Msk            (0xffffffffUL)            /*!< KEY (Bitfield-Mask: 0xffffffff)                       */
/* ==========================================================  SR2  ========================================================== */
#define FLASH_SR2_EOP_Pos                 (5UL)                     /*!< EOP (Bit 5)                                           */
#define FLASH_SR2_EOP_Msk                 (0x20UL)                  /*!< EOP (Bitfield-Mask: 0x01)                             */
#define FLASH_SR2_BUSY_Pos                (0UL)                     /*!< BUSY (Bit 0)                                          */
#define FLASH_SR2_BUSY_Msk                (0x1UL)                   /*!< BUSY (Bitfield-Mask: 0x01)                            */
/* ==========================================================  CR2  ========================================================== */
#define FLASH_CR2_LOCK_Pos                (7UL)                     /*!< LOCK (Bit 7)                                          */
#define FLASH_CR2_LOCK_Msk                (0x80UL)                  /*!< LOCK (Bitfield-Mask: 0x01)                            */
#define FLASH_CR2_START_Pos               (6UL)                     /*!< START (Bit 6)                                         */
#define FLASH_CR2_START_Msk               (0x40UL)                  /*!< START (Bitfield-Mask: 0x01)                           */
#define FLASH_CR2_BEREN_Pos               (2UL)                     /*!< BEREN (Bit 2)                                         */
#define FLASH_CR2_BEREN_Msk               (0x4UL)                   /*!< BEREN (Bitfield-Mask: 0x01)                           */
#define FLASH_CR2_SEREN_Pos               (1UL)                     /*!< SEREN (Bit 1)                                         */
#define FLASH_CR2_SEREN_Msk               (0x2UL)                   /*!< SEREN (Bitfield-Mask: 0x01)                           */
#define FLASH_CR2_PGEN_Pos                (0UL)                     /*!< PGEN (Bit 0)                                          */
#define FLASH_CR2_PGEN_Msk                (0x1UL)                   /*!< PGEN (Bitfield-Mask: 0x01)                            */
/* ==========================================================  AR2  ========================================================== */
#define FLASH_AR2_ADDR_Pos                (0UL)                     /*!< ADDR (Bit 0)                                          */
#define FLASH_AR2_ADDR_Msk                (0xffffffffUL)            /*!< ADDR (Bitfield-Mask: 0xffffffff)                      */


/* =========================================================================================================================== */
/* ================                                           GPIO                                            ================ */
/* =========================================================================================================================== */

/* =========================================================  AFR1  ========================================================== */
#define GPIO_AFR1_PIN15_Pos               (30UL)                    /*!< PIN15 (Bit 30)                                        */
#define GPIO_AFR1_PIN15_Msk               (0xc0000000UL)            /*!< PIN15 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN14_Pos               (28UL)                    /*!< PIN14 (Bit 28)                                        */
#define GPIO_AFR1_PIN14_Msk               (0x30000000UL)            /*!< PIN14 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN13_Pos               (26UL)                    /*!< PIN13 (Bit 26)                                        */
#define GPIO_AFR1_PIN13_Msk               (0xc000000UL)             /*!< PIN13 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN12_Pos               (24UL)                    /*!< PIN12 (Bit 24)                                        */
#define GPIO_AFR1_PIN12_Msk               (0x3000000UL)             /*!< PIN12 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN11_Pos               (22UL)                    /*!< PIN11 (Bit 22)                                        */
#define GPIO_AFR1_PIN11_Msk               (0xc00000UL)              /*!< PIN11 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN10_Pos               (20UL)                    /*!< PIN10 (Bit 20)                                        */
#define GPIO_AFR1_PIN10_Msk               (0x300000UL)              /*!< PIN10 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR1_PIN9_Pos                (18UL)                    /*!< PIN9 (Bit 18)                                         */
#define GPIO_AFR1_PIN9_Msk                (0xc0000UL)               /*!< PIN9 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN8_Pos                (16UL)                    /*!< PIN8 (Bit 16)                                         */
#define GPIO_AFR1_PIN8_Msk                (0x30000UL)               /*!< PIN8 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN7_Pos                (14UL)                    /*!< PIN7 (Bit 14)                                         */
#define GPIO_AFR1_PIN7_Msk                (0xc000UL)                /*!< PIN7 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN6_Pos                (12UL)                    /*!< PIN6 (Bit 12)                                         */
#define GPIO_AFR1_PIN6_Msk                (0x3000UL)                /*!< PIN6 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN5_Pos                (10UL)                    /*!< PIN5 (Bit 10)                                         */
#define GPIO_AFR1_PIN5_Msk                (0xc00UL)                 /*!< PIN5 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN4_Pos                (8UL)                     /*!< PIN4 (Bit 8)                                          */
#define GPIO_AFR1_PIN4_Msk                (0x300UL)                 /*!< PIN4 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN3_Pos                (6UL)                     /*!< PIN3 (Bit 6)                                          */
#define GPIO_AFR1_PIN3_Msk                (0xc0UL)                  /*!< PIN3 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN2_Pos                (4UL)                     /*!< PIN2 (Bit 4)                                          */
#define GPIO_AFR1_PIN2_Msk                (0x30UL)                  /*!< PIN2 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN1_Pos                (2UL)                     /*!< PIN1 (Bit 2)                                          */
#define GPIO_AFR1_PIN1_Msk                (0xcUL)                   /*!< PIN1 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFR1_PIN0_Pos                (0UL)                     /*!< PIN0 (Bit 0)                                          */
#define GPIO_AFR1_PIN0_Msk                (0x3UL)                   /*!< PIN0 (Bitfield-Mask: 0x03)                            */
/* =========================================================  AFR2  ========================================================== */
#define GPIO_AFR2_PIN31_Pos               (30UL)                    /*!< PIN31 (Bit 30)                                        */
#define GPIO_AFR2_PIN31_Msk               (0xc0000000UL)            /*!< PIN31 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN30_Pos               (28UL)                    /*!< PIN30 (Bit 28)                                        */
#define GPIO_AFR2_PIN30_Msk               (0x30000000UL)            /*!< PIN30 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN29_Pos               (26UL)                    /*!< PIN29 (Bit 26)                                        */
#define GPIO_AFR2_PIN29_Msk               (0xc000000UL)             /*!< PIN29 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN28_Pos               (24UL)                    /*!< PIN28 (Bit 24)                                        */
#define GPIO_AFR2_PIN28_Msk               (0x3000000UL)             /*!< PIN28 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN27_Pos               (22UL)                    /*!< PIN27 (Bit 22)                                        */
#define GPIO_AFR2_PIN27_Msk               (0xc00000UL)              /*!< PIN27 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN26_Pos               (20UL)                    /*!< PIN26 (Bit 20)                                        */
#define GPIO_AFR2_PIN26_Msk               (0x300000UL)              /*!< PIN26 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN25_Pos               (18UL)                    /*!< PIN25 (Bit 18)                                        */
#define GPIO_AFR2_PIN25_Msk               (0xc0000UL)               /*!< PIN25 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN24_Pos               (16UL)                    /*!< PIN24 (Bit 16)                                        */
#define GPIO_AFR2_PIN24_Msk               (0x30000UL)               /*!< PIN24 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN23_Pos               (14UL)                    /*!< PIN23 (Bit 14)                                        */
#define GPIO_AFR2_PIN23_Msk               (0xc000UL)                /*!< PIN23 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN22_Pos               (12UL)                    /*!< PIN22 (Bit 12)                                        */
#define GPIO_AFR2_PIN22_Msk               (0x3000UL)                /*!< PIN22 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN21_Pos               (10UL)                    /*!< PIN21 (Bit 10)                                        */
#define GPIO_AFR2_PIN21_Msk               (0xc00UL)                 /*!< PIN21 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN20_Pos               (8UL)                     /*!< PIN20 (Bit 8)                                         */
#define GPIO_AFR2_PIN20_Msk               (0x300UL)                 /*!< PIN20 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN19_Pos               (6UL)                     /*!< PIN19 (Bit 6)                                         */
#define GPIO_AFR2_PIN19_Msk               (0xc0UL)                  /*!< PIN19 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN18_Pos               (4UL)                     /*!< PIN18 (Bit 4)                                         */
#define GPIO_AFR2_PIN18_Msk               (0x30UL)                  /*!< PIN18 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN17_Pos               (2UL)                     /*!< PIN17 (Bit 2)                                         */
#define GPIO_AFR2_PIN17_Msk               (0xcUL)                   /*!< PIN17 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFR2_PIN16_Pos               (0UL)                     /*!< PIN16 (Bit 0)                                         */
#define GPIO_AFR2_PIN16_Msk               (0x3UL)                   /*!< PIN16 (Bitfield-Mask: 0x03)                           */
/* ========================================================  AMSELR  ========================================================= */
#define GPIO_AMSELR_PIN31_Pos             (31UL)                    /*!< PIN31 (Bit 31)                                        */
#define GPIO_AMSELR_PIN31_Msk             (0x80000000UL)            /*!< PIN31 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN30_Pos             (30UL)                    /*!< PIN30 (Bit 30)                                        */
#define GPIO_AMSELR_PIN30_Msk             (0x40000000UL)            /*!< PIN30 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN29_Pos             (29UL)                    /*!< PIN29 (Bit 29)                                        */
#define GPIO_AMSELR_PIN29_Msk             (0x20000000UL)            /*!< PIN29 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN28_Pos             (28UL)                    /*!< PIN28 (Bit 28)                                        */
#define GPIO_AMSELR_PIN28_Msk             (0x10000000UL)            /*!< PIN28 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN27_Pos             (27UL)                    /*!< PIN27 (Bit 27)                                        */
#define GPIO_AMSELR_PIN27_Msk             (0x8000000UL)             /*!< PIN27 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN26_Pos             (26UL)                    /*!< PIN26 (Bit 26)                                        */
#define GPIO_AMSELR_PIN26_Msk             (0x4000000UL)             /*!< PIN26 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN25_Pos             (25UL)                    /*!< PIN25 (Bit 25)                                        */
#define GPIO_AMSELR_PIN25_Msk             (0x2000000UL)             /*!< PIN25 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN24_Pos             (24UL)                    /*!< PIN24 (Bit 24)                                        */
#define GPIO_AMSELR_PIN24_Msk             (0x1000000UL)             /*!< PIN24 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN23_Pos             (23UL)                    /*!< PIN23 (Bit 23)                                        */
#define GPIO_AMSELR_PIN23_Msk             (0x800000UL)              /*!< PIN23 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN22_Pos             (22UL)                    /*!< PIN22 (Bit 22)                                        */
#define GPIO_AMSELR_PIN22_Msk             (0x400000UL)              /*!< PIN22 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN21_Pos             (21UL)                    /*!< PIN21 (Bit 21)                                        */
#define GPIO_AMSELR_PIN21_Msk             (0x200000UL)              /*!< PIN21 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN20_Pos             (20UL)                    /*!< PIN20 (Bit 20)                                        */
#define GPIO_AMSELR_PIN20_Msk             (0x100000UL)              /*!< PIN20 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN19_Pos             (19UL)                    /*!< PIN19 (Bit 19)                                        */
#define GPIO_AMSELR_PIN19_Msk             (0x80000UL)               /*!< PIN19 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN18_Pos             (18UL)                    /*!< PIN18 (Bit 18)                                        */
#define GPIO_AMSELR_PIN18_Msk             (0x40000UL)               /*!< PIN18 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN17_Pos             (17UL)                    /*!< PIN17 (Bit 17)                                        */
#define GPIO_AMSELR_PIN17_Msk             (0x20000UL)               /*!< PIN17 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN16_Pos             (16UL)                    /*!< PIN16 (Bit 16)                                        */
#define GPIO_AMSELR_PIN16_Msk             (0x10000UL)               /*!< PIN16 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN15_Pos             (15UL)                    /*!< PIN15 (Bit 15)                                        */
#define GPIO_AMSELR_PIN15_Msk             (0x8000UL)                /*!< PIN15 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN14_Pos             (14UL)                    /*!< PIN14 (Bit 14)                                        */
#define GPIO_AMSELR_PIN14_Msk             (0x4000UL)                /*!< PIN14 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN13_Pos             (13UL)                    /*!< PIN13 (Bit 13)                                        */
#define GPIO_AMSELR_PIN13_Msk             (0x2000UL)                /*!< PIN13 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN12_Pos             (12UL)                    /*!< PIN12 (Bit 12)                                        */
#define GPIO_AMSELR_PIN12_Msk             (0x1000UL)                /*!< PIN12 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN11_Pos             (11UL)                    /*!< PIN11 (Bit 11)                                        */
#define GPIO_AMSELR_PIN11_Msk             (0x800UL)                 /*!< PIN11 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN10_Pos             (10UL)                    /*!< PIN10 (Bit 10)                                        */
#define GPIO_AMSELR_PIN10_Msk             (0x400UL)                 /*!< PIN10 (Bitfield-Mask: 0x01)                           */
#define GPIO_AMSELR_PIN9_Pos              (9UL)                     /*!< PIN9 (Bit 9)                                          */
#define GPIO_AMSELR_PIN9_Msk              (0x200UL)                 /*!< PIN9 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN8_Pos              (8UL)                     /*!< PIN8 (Bit 8)                                          */
#define GPIO_AMSELR_PIN8_Msk              (0x100UL)                 /*!< PIN8 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN7_Pos              (7UL)                     /*!< PIN7 (Bit 7)                                          */
#define GPIO_AMSELR_PIN7_Msk              (0x80UL)                  /*!< PIN7 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN6_Pos              (6UL)                     /*!< PIN6 (Bit 6)                                          */
#define GPIO_AMSELR_PIN6_Msk              (0x40UL)                  /*!< PIN6 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN5_Pos              (5UL)                     /*!< PIN5 (Bit 5)                                          */
#define GPIO_AMSELR_PIN5_Msk              (0x20UL)                  /*!< PIN5 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN4_Pos              (4UL)                     /*!< PIN4 (Bit 4)                                          */
#define GPIO_AMSELR_PIN4_Msk              (0x10UL)                  /*!< PIN4 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN3_Pos              (3UL)                     /*!< PIN3 (Bit 3)                                          */
#define GPIO_AMSELR_PIN3_Msk              (0x8UL)                   /*!< PIN3 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN2_Pos              (2UL)                     /*!< PIN2 (Bit 2)                                          */
#define GPIO_AMSELR_PIN2_Msk              (0x4UL)                   /*!< PIN2 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN1_Pos              (1UL)                     /*!< PIN1 (Bit 1)                                          */
#define GPIO_AMSELR_PIN1_Msk              (0x2UL)                   /*!< PIN1 (Bitfield-Mask: 0x01)                            */
#define GPIO_AMSELR_PIN0_Pos              (0UL)                     /*!< PIN0 (Bit 0)                                          */
#define GPIO_AMSELR_PIN0_Msk              (0x1UL)                   /*!< PIN0 (Bitfield-Mask: 0x01)                            */
/* =========================================================  AFGR1  ========================================================= */
#define GPIO_AFGR1_PIN15_Pos              (30UL)                    /*!< PIN15 (Bit 30)                                        */
#define GPIO_AFGR1_PIN15_Msk              (0xc0000000UL)            /*!< PIN15 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN14_Pos              (28UL)                    /*!< PIN14 (Bit 28)                                        */
#define GPIO_AFGR1_PIN14_Msk              (0x30000000UL)            /*!< PIN14 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN13_Pos              (26UL)                    /*!< PIN13 (Bit 26)                                        */
#define GPIO_AFGR1_PIN13_Msk              (0xc000000UL)             /*!< PIN13 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN12_Pos              (24UL)                    /*!< PIN12 (Bit 24)                                        */
#define GPIO_AFGR1_PIN12_Msk              (0x3000000UL)             /*!< PIN12 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN11_Pos              (22UL)                    /*!< PIN11 (Bit 22)                                        */
#define GPIO_AFGR1_PIN11_Msk              (0xc00000UL)              /*!< PIN11 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN10_Pos              (20UL)                    /*!< PIN10 (Bit 20)                                        */
#define GPIO_AFGR1_PIN10_Msk              (0x300000UL)              /*!< PIN10 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR1_PIN9_Pos               (18UL)                    /*!< PIN9 (Bit 18)                                         */
#define GPIO_AFGR1_PIN9_Msk               (0xc0000UL)               /*!< PIN9 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN8_Pos               (16UL)                    /*!< PIN8 (Bit 16)                                         */
#define GPIO_AFGR1_PIN8_Msk               (0x30000UL)               /*!< PIN8 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN7_Pos               (14UL)                    /*!< PIN7 (Bit 14)                                         */
#define GPIO_AFGR1_PIN7_Msk               (0xc000UL)                /*!< PIN7 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN6_Pos               (12UL)                    /*!< PIN6 (Bit 12)                                         */
#define GPIO_AFGR1_PIN6_Msk               (0x3000UL)                /*!< PIN6 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN5_Pos               (10UL)                    /*!< PIN5 (Bit 10)                                         */
#define GPIO_AFGR1_PIN5_Msk               (0xc00UL)                 /*!< PIN5 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN4_Pos               (8UL)                     /*!< PIN4 (Bit 8)                                          */
#define GPIO_AFGR1_PIN4_Msk               (0x300UL)                 /*!< PIN4 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN3_Pos               (6UL)                     /*!< PIN3 (Bit 6)                                          */
#define GPIO_AFGR1_PIN3_Msk               (0xc0UL)                  /*!< PIN3 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN2_Pos               (4UL)                     /*!< PIN2 (Bit 4)                                          */
#define GPIO_AFGR1_PIN2_Msk               (0x30UL)                  /*!< PIN2 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN1_Pos               (2UL)                     /*!< PIN1 (Bit 2)                                          */
#define GPIO_AFGR1_PIN1_Msk               (0xcUL)                   /*!< PIN1 (Bitfield-Mask: 0x03)                            */
#define GPIO_AFGR1_PIN0_Pos               (0UL)                     /*!< PIN0 (Bit 0)                                          */
#define GPIO_AFGR1_PIN0_Msk               (0x3UL)                   /*!< PIN0 (Bitfield-Mask: 0x03)                            */
/* =========================================================  AFGR2  ========================================================= */
#define GPIO_AFGR2_PIN31_Pos              (30UL)                    /*!< PIN31 (Bit 30)                                        */
#define GPIO_AFGR2_PIN31_Msk              (0xc0000000UL)            /*!< PIN31 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN30_Pos              (28UL)                    /*!< PIN30 (Bit 28)                                        */
#define GPIO_AFGR2_PIN30_Msk              (0x30000000UL)            /*!< PIN30 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN29_Pos              (26UL)                    /*!< PIN29 (Bit 26)                                        */
#define GPIO_AFGR2_PIN29_Msk              (0xc000000UL)             /*!< PIN29 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN28_Pos              (24UL)                    /*!< PIN28 (Bit 24)                                        */
#define GPIO_AFGR2_PIN28_Msk              (0x3000000UL)             /*!< PIN28 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN27_Pos              (22UL)                    /*!< PIN27 (Bit 22)                                        */
#define GPIO_AFGR2_PIN27_Msk              (0xc00000UL)              /*!< PIN27 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN26_Pos              (20UL)                    /*!< PIN26 (Bit 20)                                        */
#define GPIO_AFGR2_PIN26_Msk              (0x300000UL)              /*!< PIN26 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN25_Pos              (18UL)                    /*!< PIN25 (Bit 18)                                        */
#define GPIO_AFGR2_PIN25_Msk              (0xc0000UL)               /*!< PIN25 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN24_Pos              (16UL)                    /*!< PIN24 (Bit 16)                                        */
#define GPIO_AFGR2_PIN24_Msk              (0x30000UL)               /*!< PIN24 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN23_Pos              (14UL)                    /*!< PIN23 (Bit 14)                                        */
#define GPIO_AFGR2_PIN23_Msk              (0xc000UL)                /*!< PIN23 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN22_Pos              (12UL)                    /*!< PIN22 (Bit 12)                                        */
#define GPIO_AFGR2_PIN22_Msk              (0x3000UL)                /*!< PIN22 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN21_Pos              (10UL)                    /*!< PIN21 (Bit 10)                                        */
#define GPIO_AFGR2_PIN21_Msk              (0xc00UL)                 /*!< PIN21 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN20_Pos              (8UL)                     /*!< PIN20 (Bit 8)                                         */
#define GPIO_AFGR2_PIN20_Msk              (0x300UL)                 /*!< PIN20 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN19_Pos              (6UL)                     /*!< PIN19 (Bit 6)                                         */
#define GPIO_AFGR2_PIN19_Msk              (0xc0UL)                  /*!< PIN19 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN18_Pos              (4UL)                     /*!< PIN18 (Bit 4)                                         */
#define GPIO_AFGR2_PIN18_Msk              (0x30UL)                  /*!< PIN18 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN17_Pos              (2UL)                     /*!< PIN17 (Bit 2)                                         */
#define GPIO_AFGR2_PIN17_Msk              (0xcUL)                   /*!< PIN17 (Bitfield-Mask: 0x03)                           */
#define GPIO_AFGR2_PIN16_Pos              (0UL)                     /*!< PIN16 (Bit 0)                                         */
#define GPIO_AFGR2_PIN16_Msk              (0x3UL)                   /*!< PIN16 (Bitfield-Mask: 0x03)                           */


/* =========================================================================================================================== */
/* ================                                            RCC                                            ================ */
/* =========================================================================================================================== */

/* ========================================================  AHBEN1  ========================================================= */
#define RCC_AHBEN1_GPIOAEN_Pos            (16UL)                    /*!< GPIOAEN (Bit 16)                                      */
#define RCC_AHBEN1_GPIOAEN_Msk            (0x10000UL)               /*!< GPIOAEN (Bitfield-Mask: 0x01)                         */
/* ========================================================  APBEN5  ========================================================= */
#define RCC_APBEN5_UART1EN_Pos            (0UL)                     /*!< UART1EN (Bit 0)                                       */
#define RCC_APBEN5_UART1EN_Msk            (0x1UL)                   /*!< UART1EN (Bitfield-Mask: 0x01)                         */
/* ========================================================  UNLOCKR  ======================================================== */
#define RCC_UNLOCKR_KEY_Pos               (0UL)                     /*!< KEY (Bit 0)                                           */
#define RCC_UNLOCKR_KEY_Msk               (0xffffffffUL)            /*!< KEY (Bitfield-Mask: 0xffffffff)                       */


/* =========================================================================================================================== */
/* ================                                          SYSCTRL                                          ================ */
/* =========================================================================================================================== */

/* ========================================================  EPROTR3  ======================================================== */
#define SYSCTRL_EPROTR3_GPIOADIS_Pos      (0UL)                     /*!< GPIOADIS (Bit 0)                                      */
#define SYSCTRL_EPROTR3_GPIOADIS_Msk      (0x1UL)                   /*!< GPIOADIS (Bitfield-Mask: 0x01)                        */
/* ========================================================  UNLOCKR  ======================================================== */
#define SYSCTRL_UNLOCKR_KEY_Pos           (0UL)                     /*!< KEY (Bit 0)                                           */
#define SYSCTRL_UNLOCKR_KEY_Msk           (0xffffffffUL)            /*!< KEY (Bitfield-Mask: 0xffffffff)                       */


/* =========================================================================================================================== */
/* ================                                           UART                                            ================ */
/* =========================================================================================================================== */

/* ==========================================================  CR1  ========================================================== */
#define UART_CR1_RST_Pos                  (1UL)                     /*!< RST (Bit 1)                                           */
#define UART_CR1_RST_Msk                  (0x2UL)                   /*!< RST (Bitfield-Mask: 0x01)                             */
/* ==========================================================  CR2  ========================================================== */
#define UART_CR2_OSR_Pos                  (24UL)                    /*!< OSR (Bit 24)                                          */
#define UART_CR2_OSR_Msk                  (0x1f000000UL)            /*!< OSR (Bitfield-Mask: 0x1f)                             */
#define UART_CR2_DESEN_Pos                (17UL)                    /*!< DESEN (Bit 17)                                        */
#define UART_CR2_DESEN_Msk                (0x20000UL)               /*!< DESEN (Bitfield-Mask: 0x01)                           */
#define UART_CR2_DIV_Pos                  (0UL)                     /*!< DIV (Bit 0)                                           */
#define UART_CR2_DIV_Msk                  (0x1fffUL)                /*!< DIV (Bitfield-Mask: 0x1fff)                           */
/* =========================================================  CSR1  ========================================================== */
#define UART_CSR1_TXRDY_Pos               (23UL)                    /*!< TXRDY (Bit 23)                                        */
#define UART_CSR1_TXRDY_Msk               (0x800000UL)              /*!< TXRDY (Bitfield-Mask: 0x01)                           */
#define UART_CSR1_TXC_Pos                 (22UL)                    /*!< TXC (Bit 22)                                          */
#define UART_CSR1_TXC_Msk                 (0x400000UL)              /*!< TXC (Bitfield-Mask: 0x01)                             */
/* ==========================================================  CR3  ========================================================== */
#define UART_CR3_TXEN_Pos                 (19UL)                    /*!< TXEN (Bit 19)                                         */
#define UART_CR3_TXEN_Msk                 (0x80000UL)               /*!< TXEN (Bitfield-Mask: 0x01)                            */
/* ==========================================================  DR  =========================================================== */
#define UART_DR_DATA_Pos                  (0UL)                     /*!< DATA (Bit 0)                                          */
#define UART_DR_DATA_Msk                  (0xffUL)                  /*!< DATA (Bitfield-Mask: 0xff)                            */

/** @} */ /* End of group PosMask_peripherals */


#ifdef __cplusplus
}
#endif

#endif /* RT32F7_H */


/** @} */ /* End of group rt32f7 */

/** @} */ /* End of group RealTime Semiconductor Co. LTD */
